server:
  port: 8081
  error:
    whitelabel:
      enabled: false
    include-message: always

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP:true}

    hostname: ${EUREKA_HOSTNAME:localhost}

    ip-address: ${EUREKA_IP:127.0.0.1}

    non-secure-port: 8081
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

spring:
  application:
    name: book-service

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://localhost:5432/books_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  logging:
    level:
      org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    health:
      show-details: always