server:
  port: 8085

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5434/auth_db
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP:true}

    hostname: ${EUREKA_HOSTNAME:localhost}

    ip-address: ${EUREKA_IP:127.0.0.1}

    non-secure-port: 8085
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10


jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 часа

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    health:
      show-details: always