spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library
      auto-index-creation: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
    ru.otus.hw: DEBUG